### ISSUE TITLE
I'm not able to create Apple certificates. Can someone help me with a guide or reference

### ISSUE THREAD

**Issue by yepesasecas** [tuvistavie/pushex#5]
Im trying to create the Apple certificate, but I'm not able to make it work. I follow multiple tutorial from different languages, but they don't work. pushex.

thank you

**Comment by tuvistavie** [comment]
Hi,
What part of the certification are you blocked at?

**Comment by yepesasecas** [comment]
I have been following multiple guides. This are the steps I took (I think, I'm doing it totally wrong)

1. I created an Apple Push Notification service SSL (Sandbox & Production)
<img width="1042" alt="screen shot 2017-05-23 at 9 28 07 am" src="https://cloud.githubusercontent.com/assets/1679292/26359224/7ed3bcc4-3f9a-11e7-9bd4-0b2a4ff3ab27.png">

2. Then I added to my Keychain.

3. I found this guide: 
<img width="882" alt="screen shot 2017-05-23 at 9 31 48 am" src="https://cloud.githubusercontent.com/assets/1679292/26359296/b34e88da-3f9a-11e7-9092-d718d72e737d.png">

4. Then tried to export as .p12, not allowed.
<img width="875" alt="screen shot 2017-05-23 at 9 32 55 am" src="https://cloud.githubusercontent.com/assets/1679292/26359358/de7edffa-3f9a-11e7-915c-0a143943ca6e.png">

**Comment by tuvistavie** [comment]
This looks perfectly fine, but you do not need the last step.
Once you have `cert.pem` and `key_unencrypted.pem`, you only need to configure your app, for example:

```elixir
config :pushex,
  apns: [
    default_app: "my_app",
    apps: [
      [name: "my_app",
       env: :dev,
       certfile: Path.expand("../cert.pem", __DIR__),
       keyfile: Path.expand("../key_unencrypted.pem", __DIR__),
       pool_size: 5]
    ]
  ]
```

With the above config, `cert.pem` and `key_unencrypted.pem` should be placed in your project root directory. Of course you can change this to fit your needs.

**Comment by yepesasecas** [comment]
thank you for your help. @tuvistavie :)

also this helped me: https://stackoverflow.com/questions/21250510/generate-pem-file-used-to-setup-apple-push-notification
