### ISSUE TITLE
Vex validation error

### ISSUE THREAD

**Issue by mrcnkoba** [tuvistavie/pushex#6]
Hello! I'm trying to get Pushex to work and I started with the docs. (of course I replace `auth_key` and `to` fields).

**Here is what I want to do:**
`app = %Pushex.GCM.App{name: "a_unique_name_you_like", auth_key: "a GCM API auth key"}
Pushex.push(%{title: "my_title", body: "my_body"}, to: "registration_id", with_app: app)`

**The result that I'm getting is the following:**
`** (Vex.InvalidValidatorError) validator :type from sources [Vex.Validators]
             lib/vex.ex:71: Vex.validator/1
             lib/vex.ex:46: Vex.result/4
    (elixir) lib/enum.ex:1183: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1183: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1187: anonymous fn/3 in Enum.map/2
    (stdlib) lists.erl:1262: :lists.foldl/3
    (elixir) lib/enum.ex:1187: Enum.map/2
             lib/vex.ex:31: Vex.results/2
             lib/vex.ex:24: Vex.errors/2
             lib/pushex/util.ex:8: Pushex.Util.validate/2
             lib/pushex/util.ex:27: Pushex.Util.create_struct!/2
             lib/pushex/helpers.ex:61: Pushex.Helpers.do_send_notification/3`

Could anyone point me into a good direction? Is this a bug or my fault 😄 ?

**Comment by tuvistavie** [comment]
Hi,
Is the `:pushex` application running? In Elixir 1.4 it should be running by default when you add it to your mix dependencies, but in Elixir <= 1.3 you must add it to the applications in `mix.exs`.
If it is, could you show me what `Application.get_env(:vex, :sources)` returns please?

Thank you.

**Comment by mrcnkoba** [comment]
Hey @tuvistavie 
I'm on Elixir 1.2 and indeed it was not running, but after that I ran into an issue described here: https://github.com/tuvistavie/pushex/issues/4. Which was solved by your suggestion.
Maybe we could update docs to inform users on Elixir <= 1.3 about this additional step? I'd be happy to create a pull request for the documentation update.

**Comment by tuvistavie** [comment]
There is a small note in the README saying

> Then, add :pushex to your applications.

but if you want to make it clearer a PR would of course be very appreciated.
