### ISSUE TITLE
FCM Support planned?

### ISSUE THREAD

**Issue by danubekas** [tuvistavie/pushex#8]
Hi,

are you planning to support fcm? 
The implmentation is very similar to gcm. I think the endpoint is the only difference right now.

**Comment by tuvistavie** [comment]
Hi, 
If it is only an endpoint change, I think it should already be supported through configuration.
Could you please give the following a try and let me know how it goes.

```elixir
config :pushex,
  gcm: [
    endpoint: "fcm endpoint"
  ]
```

**Comment by danubekas** [comment]
Ok,
I did not realize that the option was configurable. I will try it out tonight.

**Comment by danubekas** [comment]
works like a charm ;)
